# Generated by Django 2.0.8 on 2019-05-01 15:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_ocupacion', models.DateField(default=datetime.date.today)),
                ('fecha_publicacion', models.DateField(default=datetime.date.today)),
                ('foto', models.URLField()),
                ('precioBase', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
