# Generated by Django 2.0.8 on 2019-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='residencia',
            name='precioBase',
            field=models.FloatField(),
        ),
    ]
