# Generated by Django 2.0.8 on 2019-05-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0002_auto_20190501_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='id',
        ),
        migrations.AddField(
            model_name='residencia',
            name='ubicacion',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='residencias.Ubicacion'),
        ),
    ]
