# Generated by Django 2.0.8 on 2019-05-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0003_auto_20190501_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='ubicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='residencias.Ubicacion'),
        ),
    ]
